### ISSUE TITLE
Returns list of generated keys of the batch insert

### ISSUE THREAD

**Issue by sameeragunarathne** [wso2/carbon-data#179]
**Description:**

When using the batch insert(enableBatchRequests="true") to insert list of data to the database in WSO2 DSS each insert should generate the id once the record is inserted. Need to return those generated ids with data service response.

**Suggested Labels:**

Improvements

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by prabushi** [comment]
This fix is available in EI 6.3.0-m3 release.
