### ISSUE TITLE
Resource leak - FileInputStream is not closed on method exit

### ISSUE THREAD

**Issue by malshaniS** [wso2/carbon-data#218]
**Description:**
Resource leak due to FileInputStream is not closed on method exit. Therefore cannot delete resource in Windows environment.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**  
OS: Windows 2016  

**Steps to reproduce:**

**Related Issues:**

**Comment by kasunbg** [comment]
Fixed in #217.
